**Consider the following Python dictionary data and Python list labels:**

data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
        'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

**1. Create a DataFrame birds from this dictionary data which has the index labels.**

In [1]:
import pandas as pd
import numpy as np

data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
        'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

birds = pd.DataFrame(data, index=labels)
birds

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

**2. Display a summary of the basic information about birds DataFrame and its data.**

In [2]:
birds.info()
birds.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birds     10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

         birds       age     visits priority
count       10  8.000000  10.000000       10
unique       3       NaN        NaN        2
top     Cranes       NaN        NaN       no
freq         4       NaN        NaN        6
mean       NaN  4.437500   2.900000      NaN
std        NaN  2.007797   0.875595      NaN
min        NaN  1.500000   2.000000      NaN
25%        NaN  3.375000   2.000000      NaN
50%        NaN  4.000000   3.000000      NaN
75%        NaN  5.625000   3.750000      NaN
max        NaN  8.000000   4.000000      NaN

**3. Print the first 2 rows of the birds dataframe **

In [3]:
birds.head(2)

    birds  age  visits priority
a  Cranes  3.5       2      yes
b  Cranes  4.0       4      yes

**4. Print all the rows with only 'birds' and 'age' columns from the dataframe**

In [4]:
birds[['birds', 'age']]

        birds  age
a      Cranes  3.5
b      Cranes  4.0
c     plovers  1.5
d  spoonbills  NaN
e  spoonbills  6.0
f      Cranes  3.0
g     plovers  5.5
h      Cranes  NaN
i  spoonbills  8.0
j  spoonbills  4.0

**5. select [2, 3, 7] rows and in columns ['birds', 'age', 'visits']**

In [5]:
birds.iloc[[2, 3, 7]][['birds', 'age', 'visits']]

        birds  age  visits
c     plovers  1.5       3
d  spoonbills  NaN       4
h      Cranes  NaN       2

**6. select the rows where the number of visits is less than 4**

In [6]:
birds[birds['visits'] < 4]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

**7. select the rows with columns ['birds', 'visits'] where the age is missing i.e NaN**

In [7]:
birds.loc[birds['age'].isna(), ['birds', 'visits']]

        birds  visits
d  spoonbills       4
h      Cranes       2

**8. Select the rows where the birds is a Cranes and the age is less than 4**

In [8]:
birds[(birds['birds'] == 'Cranes') & (birds['age'] < 4)]

    birds  age  visits priority
a  Cranes  3.5       2      yes
f  Cranes  3.0       4       no

**9. Select the rows the age is between 2 and 4(inclusive)**

In [9]:
birds[birds['age'].between(2, 4, inclusive='both')]

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
f      Cranes  3.0       4       no
j  spoonbills  4.0       2       no

**10. Find the total number of visits of the bird Cranes**

In [10]:
birds.loc[birds['birds'] == 'Cranes', 'visits'].sum()

np.int64(12)

**11. Calculate the mean age for each different birds in dataframe.**

In [11]:
birds.groupby('birds')['age'].mean()

birds
Cranes        3.5
plovers       3.5
spoonbills    6.0
Name: age, dtype: float64

**12. Append a new row 'k' to dataframe with your choice of values for each column. Then delete that row to return the original DataFrame.**

In [12]:
new_row = pd.DataFrame(
    {'birds': ['parrots'], 'age': [2.5], 'visits': [3], 'priority': ['yes']},
    index=['k']
)

birds_with_k = pd.concat([birds, new_row])
print("DataFrame after adding row 'k':")
display(birds_with_k)

birds_without_k = birds_with_k.drop(index='k')
print("\nOriginal DataFrame restored:")
display(birds_without_k)

DataFrame after adding row 'k':

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k     parrots  2.5       3      yes

Original DataFrame restored:

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

**13. Find the number of each type of birds in dataframe (Counts)**

In [13]:
birds['birds'].value_counts()

birds
Cranes        4
spoonbills    4
plovers       2
Name: count, dtype: int64

**14. Sort dataframe (birds) first by the values in the 'age' in decending order, then by the value in the 'visits' column in ascending order.**

In [14]:
birds.sort_values(by=['age', 'visits'], ascending=[False, True])

        birds  age  visits priority
i  spoonbills  8.0       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
j  spoonbills  4.0       2       no
b      Cranes  4.0       4      yes
a      Cranes  3.5       2      yes
f      Cranes  3.0       4       no
c     plovers  1.5       3       no
h      Cranes  NaN       2      yes
d  spoonbills  NaN       4      yes

**15. Replace the priority column values with'yes' should be 1 and 'no' should be 0**

In [15]:
birds['priority'] = birds['priority'].map({'yes': 1, 'no': 0})
birds

        birds  age  visits  priority
a      Cranes  3.5       2         1
b      Cranes  4.0       4         1
c     plovers  1.5       3         0
d  spoonbills  NaN       4         1
e  spoonbills  6.0       3         0
f      Cranes  3.0       4         0
g     plovers  5.5       2         0
h      Cranes  NaN       2         1
i  spoonbills  8.0       3         0
j  spoonbills  4.0       2         0

**16. In the 'birds' column, change the 'Cranes' entries to 'trumpeters'.**

In [16]:
birds['birds'] = birds['birds'].replace('Cranes', 'trumpeters')
birds

        birds  age  visits  priority
a  trumpeters  3.5       2         1
b  trumpeters  4.0       4         1
c     plovers  1.5       3         0
d  spoonbills  NaN       4         1
e  spoonbills  6.0       3         0
f  trumpeters  3.0       4         0
g     plovers  5.5       2         0
h  trumpeters  NaN       2         1
i  spoonbills  8.0       3         0
j  spoonbills  4.0       2         0